// <auto-generated />
namespace Brighteye.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PPP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PPP));
        
        string IMigrationMetadata.Id
        {
            get { return "202311070809107_PPP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
